FROM debian:stretch-slim

LABEL maintainer="isuftin@usgs.gov"

RUN apt-get update && \
      apt-get upgrade -y && \
      apt-get install nginx -y && \
      apt-get clean

CMD ["nginx", "-g", "daemon off;"]
